export const cartTypes = {
    CART_TOGGLE_CART_HIDDEN: 'CART_TOGGLE_CART_HIDDEN',
    CART_ADD_ITEM: 'CART_ADD_ITEM',
    CART_REMOVE_ITEM: 'CART_REMOVE_ITEM',
    CART_CLEAR_ITEM_FROM_CART: 'CART_CLEAR_ITEM_FROM_CART'
};