export const cartTypes = {
    CART_TOGGLE_CART_HIDDEN: 'CART_TOGGLE_CART_HIDDEN',
    CART_ADD_ITEM: 'CART_ADD_ITEM',
    CART_REMOVE_ITEM: 'CART_REMOVE_ITEM',
    CART_SAGA_START: 'CART_SAGA_START',
    CART_REQUEST: 'CART_REQUEST',
    CART_RECEIVED: 'CART_RECEIVED',
    CART_ERROR: 'CART_ERROR'
};