export const cartTypes = {
    CART_TOGGLE_CART_HIDDEN: 'CART_TOGGLE_CART_HIDDEN',
    CART_SAGA_START: 'CART_SAGA_START',
    CART_REQUEST: 'CART_REQUEST',
    CART_RECEIVED: 'CART_RECEIVED',
    CART_ERROR: 'CART_ERROR'
};