export const registrationTypes = {
    REGISTRATION_USER_SAGA_START: 'REGISTRATION_USER_SAGA_START',
    REGISTRATION_USER_REQUEST: 'REGISTRATION_USER_REQUEST',
    REGISTRATION_USER_RECEIVED: 'REGISTRATION_USER_RECEIVED',
    REGISTRATION_USER_ERROR: 'REGISTRATION_USER_ERROR'
};