export const UserActionTypes = {
    SET_AUTHENTICATION: 'SET_AUTHENTICATION',
    IS_AUTHENTICATION: 'IS_AUTHENTICATION',

    LOGIN_REDUX_SAGA_START: 'LOGIN_REDUX_SAGA_START',
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_RECEIVED: 'LOGIN_RECEIVED',
    LOGIN_ERROR: 'LOGIN_ERROR',
};